/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyFirstRustClass */

#ifndef _Included_MyFirstRustClass
#define _Included_MyFirstRustClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyFirstRustClass
 * Method:    exposed_function
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MyFirstRustClass_exposed_1function
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
